---
- name: playbook
  hosts: rh01
  become: yes
  vars:
    atlas_project_id: "67cb5fc228b465316458be99"
    atlas_provider: "AZURE"
    atlas_region: "EUROPE_WEST"
    atlas_instance_size: "M10"
    atlas_disk_size: 10
    atlas_public_key: "rcncprnf"
    atlas_private_key: "f0af8edb-897d-4985-ac86-e7b94a125f99" 
    DB_PASSWORD: "VfnMplqnE7iQJemc"
  tasks:
    - name: Set env variable DB_PASSWORD
      ansible.builtin.shell: echo "Set DB_PASSWORD"
      environment:
        DB_PASSWORD: "VfnMplqnE7iQJemc"


    - name: Update paket list
      ansible.builtin.apt:
        update_cache: yes


    - name: Install Python3
      ansible.builtin.apt:
        name: python3
        state: present


    - name: Install python3-pip
      ansible.builtin.apt:
        name: python3-pip
        state: present


    - name: Install Docker Python SDK
      ansible.builtin.pip:
        name: docker
        executable: pip3
        state: present


    - name: Install Docker
      ansible.builtin.apt:
        name: docker.io
        state: present


    - name: Adding user to docker group  
      user: name=azureuser
            groups=docker
            append=yes


    - name: Install pymongo via pip
      ansible.builtin.pip:
        name: pymongo
        state: present


    - name: Set cluster name
      set_fact:
        cluster_name: "CCII"


    - name: Configurate unrestricted access in Atlas (Whitelist 0.0.0.0/0)
      uri:
        url: "https://cloud.mongodb.com/api/atlas/v1.0/groups/{{ atlas_project_id }}/accessList"
        method: POST
        user: "{{ atlas_public_key }}"
        password: "{{ atlas_private_key }}"
        force_basic_auth: no
        headers:
          Content-Type: "application/json"
        body_format: json
        body: >
          [
            {
              "ipAddress": "0.0.0.0/0",
              "comment": "Allow all access"
            }
          ]
        status_code: 201


    - name: Create collection in database "CCII"
      shell: |
        python3 - <<'EOF'
        import os
        from pymongo import MongoClient

        db_password = os.getenv("DB_PASSWORD")
        if not db_password:
            raise ValueError("DB_PASSWORD is not set!")

        uri = f"mongodb+srv://lucaladerer:{db_password}@{{ cluster_name | lower }}.yu2co.mongodb.net/?retryWrites=true&w=majority&appName=CCII"
        client = MongoClient(uri)
        db = client["CCII"]

        if "Jokes_{{ ansible_host }}" not in db.list_collection_names():
            db.create_collection("Jokes_{{ ansible_host }}")
            db.create_collection("counters_{{ ansible_host }}")
            
            collection = db["counters_{{ ansible_host }}"]
            collection.insert_one({"_id": "totalRatings", "count": 0})
            print("Collection 'Jokes_{{ ansible_host }}' und 'counters_{{ ansible_host }}' wurde erstellt.")
        else:
            print("Collection 'Jokes_{{ ansible_host }}' existiert bereits.")

        client.close()
        EOF
      args:
        executable: /bin/bash
      environment:
        DB_PASSWORD: VfnMplqnE7iQJemc
      vars:
        cluster_name: "{{ cluster_name }}"


    - name: Start Docker container with flask app
      community.docker.docker_container:
        name: web_app
        image: lucaladerer/web_app:latest
        pull: 1
        state: started
        ports:
          - "5000:5000"
        env:
          DB_PASSWORD: VfnMplqnE7iQJemc
          COLLECTION: Jokes_{{ ansible_host }}
          COUNTERS_COLLECTION: counters_{{ ansible_host }}


    - name: Print IP and port
      ansible.builtin.debug:
        msg: "Copy the following address into your browser to access the app: {{ ansible_host }}:5000"