# Python 3.11-Image as base
FROM python:3.11-slim

# this part is used for uWSGI to work properly
RUN apt-get update && apt-get install -y \
    gcc \
    build-essential \
    python3-dev \
    libpcre3-dev \
    && rm -rf /var/lib/apt/lists/*

# Copy requirements
COPY requirements.txt requirements.txt

# Install requirements
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

COPY . .

# Set environment variable for flask app
ENV FLASK_APP=app.py

# Expose port where flask runs
EXPOSE 5000

# uWSGI command to run the app
CMD ["uwsgi", "--http", "0.0.0.0:5000", "--master", "-p", "4", "--enable-threads", "--lazy-apps", "-w", "wsgi:app"]
