# Verwende ein Python 3.11-Image als Basis
FROM python:3.11-slim

# Setze das Arbeitsverzeichnis im Container
# WORKDIR /app

# Kopiere die restlichen Dateien in das Arbeitsverzeichnis
COPY requirements.txt requirements.txt

# Installiere requirements
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

COPY . .

# Setze die Umgebungsvariable für den Flask-Server
ENV FLASK_APP=app.py

# Setze den Port, auf dem der Flask-Server laufen soll
EXPOSE 5000

# Starte den Flask-Server beim Starten des Containers
CMD [ "python3", "-m" , "flask", "run", "--host=0.0.0.0"]